CMDSCRIPT /opt/ups-orchestrator/server/scripts/upssched-cmd
PIPEFN /run/nut/upssched.pipe
LOCKFN /run/nut/upssched.lock

AT ONBATT * EXECUTE ONBATT
AT ONBATT * START-TIMER desktop_suspend_due 300
AT ONLINE * EXECUTE ONLINE
AT ONLINE * CANCEL-TIMER desktop_suspend_due
AT LOWBATT * EXECUTE LOWBATT
